- name: Fucntions Demmo
  hosts: local
  connection: local
  vars:
    PERSONS: "Ramesh, Suresh, Raheem, Joseph"
  tasks:
  - name: print vairbale value without defining it using default
    ansible.builtin.debug:
      msg: "Hello {{ PERSON | default ('Uday') }}"

  
  - name: print vairbale value by defining it using default
    ansible.builtin.debug:
      msg: "Hello {{ PERSONS | split (',') }}"
    