- name: Fucntions Demmo
  hosts: local
  connection: local
  vars:
    PERSONS: "Ramesh,Suresh,Raheem,Joseph"
  tasks:
  - name: print vairbale value without defining it using default
    ansible.builtin.debug:
      msg: "Hello {{ PERSON | default ('Uday') }}"

  
  - name: print vairbale value by defining it using default
    ansible.builtin.debug:
      msg: "Hello {{ PERSONS | split (',') }}"
  
  - name: convert map to List
    vars: 
      COURSE:
        name: ansible
        duration: 10 hours
        trainer: Shiva
    ansible.builtin.debug:
      msg: " Details are {{ COURSE | dict2items }}"
    
  - name: convert map to List
    vars: 
      COURSE:
        - { 'key': 'name', 'value': 'ansible'}
        - { 'key': 'duration', 'value': '10 hours'}
        - { 'key': 'trainer', 'value': 'Siva'}
    ansible.builtin.debug:
      msg: " Details are {{ COURSE | items2dict }}"

    