- name: understand vars prefernece
  hosts: local
  connection: local
  vars:
    GREETING: "Hello from Play"
  vars_files:
  - course.yaml
  tasks:
  - name: variables preference testing
    ansible.builtin.debug:
      msg: "This greeting is {{GREETING}}"

